### ISSUE TITLE
W08H01: Missing Test: solveMazeFrom impossible path from position to exit

### ISSUE THREAD

**Issue by LadnerJonas** [LadnerJonas/PGdP-Tests-WS21-22#34]
Homework Number: W08H01

Citation of the homework instruction:
> static Path solveMazeFrom(Maze maze, Position position):
> [....]
>**Sollte ein solcher Pfad nicht mehr existieren, soll null zurückgegeben werden.**

Additional Information:
> Maze
> [....]
> **du kannst aber davon ausgehen, dass der exit immer vom entrance aus erreichbar ist.**

Position can be != Entrance, and thus, this case has to be tested aswell.
#33 

Thanks @Mani 🏅

**Comment by 0xReself** [comment]
I would agree, the instruction describes what do do with not valid positions for solving the maze. So we need to handle the case of position != entrance. And some test for that would be great!

_Also here the link for the zulip post im getting my information from:
https://zulip.in.tum.de/#narrow/stream/864-PGdP-W08H01--.20Rekursive.20Pfade/topic/Null.20Eingaben_

**Comment by YannickWiest** [comment]
Also a test for the case: "going over the entrance" needs to be added i think. Because i think i read that it is possible for a solution path to start somewhere at the top and then  cross the entrance on its way down.

WWW
WPW
W  W
WEW
W  W
WXW

In this case P marks the starting point. I think therfore the valid solution should be 4*Dow
Correct me if im wrong

I will try to find the corresponding Zulip Post tomorrow.
I will also try to create a test and upload it by then if i somehow figure out how to do that^^

**Comment by LadnerJonas** [comment]
Yeah a zulip link would be great. :+1:
Just asked the so-called Übungsleitung: This is a valid maze and we need to be able to solve it.

**Comment by YannickWiest** [comment]
If this still needs to be converted into a test by tomorrow I will do so.

**Comment by LadnerJonas** [comment]
I am working on it. 🚀

**Comment by LadnerJonas** [comment]
Can be closed @YannickWiest @0xReself?

**Comment by 0xReself** [comment]
Yeah great work looks good to me.
