### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by amine20011111** [LadnerJonas/PGdP-Tests-WS21-22#46]
Homework Number (example: W04H01):
W12H01
Citation of the homework instruction:

Additional Information:
testMultiplication and addition are failing for me (the first ones) but the other pass.So i wanted to ask what do they test exactly

**Comment by LadnerJonas** [comment]
I have created this project in my own free time. Since my free time is limited, I cannot explain every test to every one of the 1500+ PGdP students. If you cannot even invest the time to formulate your explicit question, then I do not want to waste my time further either.

Your request only shows bad manners.
